on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment.    
      ref:  
        type: string
        required: true
        description: The tag or SHA to checkout.

jobs:

  deploy:
    name: Deploy DAGs to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref }}

    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Deploy DAGs 
      run: |
            gcloud storage cp ./dags/[!test]*.py "${{ vars.GCS_DAGS_URL }}"

#  prod_deployment:
#    name: Deploy DAGs to prod environment
#    needs: quality_checks
#    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'prod' }}
#    uses: ./.github/workflows/_deployment.yaml 
#    permissions:
#      id-token: write
#      contents: read
#    with: 
#      environment: prod
#      ref: ${{ github.sha }}
#    secrets: inherit
